// const ISODate = date => new Date(date);

module.exports = {
    "jobRequest": [
        {
            "jobrequestid": "5d2d620746fac580993b3b7b",
            "jobsnapshotid": "5d2d620646fac580993b3b79",
            "propertyname": "Sample Property",
            "address": "101 Main Street",
            "city": "San Francisco",
            "countrycode": "United States",
            "bedrooms": 3,
            "bathrooms": 2,
            "propertytype": "house",
            "accessinfo": "The lockbox with keys is at the top of the stairs, on the post opposite the front door. The code is 1234.",
            "garbageinfo": "The garbage cans are under the stairs leading up to the front door. Garbage is collected early on Monday morning.",
            "parkinginfo": "You can park your car on the street right in front of our garage. Parking is prohibited every second and fourth Monday of the month from 9am to 11am due to streetcleaning.",
            "wifiname": "WIFI Guest 2.4",
            "wifipassword": "password",
            "wifidescription": "-",
            "importantinfo": "Do not vacuum the cowhide rug in the home office - just shake it out. Vacuum all rugs, mop all hard floors, wipe all surfaces and light switches, clean all windows and glass surfaces, and disinfect toilet seats.",
            "offeredprice": 16,
            "duration": "-",
            "offeredpricecurrency": "USD",
            "canceledbyserviceprovider": "no",
            "canceledbyme": "no",
            "statusofrequest": "Pending",
            "msgtoserviceprovider": "T2",
            "scheduletime": "11:00 AM - 12:00 PM",
            "scheduleend": "07/17/2019",
            "schedulestart": "07/17/2019",
            "scheduleduration": 60,
            "jobsenddate": "07/15/2019",
            "job_title": "T2",
            "jobType": "Concierge",
            "costs": [
                {
                    "reporterName": "Nihal Test",
                    "type": "mileage",
                    "value": 10,
                    "date": "2019-07-16T06:38:49.975Z",
                },
                {
                    "reporterName": "Nihal Test",
                    "type": "mileage",
                    "value": 145,
                    "date": "2019-08-02T05:50:44.679Z",
                }
            ],
            "totalCost": 90,
            "totalMileage": 130,
            "billableTime": 40,
            "slides": "0/4",
            "tasks": "0/8",
            "verificationphotos": "0/4",
            "problemsreported": 0,
            "problemslist": [],
            "title": "Sample: Simple",
            "description": "With just 4 photos you can create a simple checklist job and still get peace of mind your tasks were completed.\nThis checklist only has photos in the finish section and lets a host know when a pro started and finished the job; conveys exactly how a host wants the property set upon finish; gives peace of mind with visual proof the tasks were completed (photo required set); and has all of the property info. \nFor an example of a more thorough checklist check out the Sample: Complex in Sample Property.",
            "actualstartdate": "-",
            "actualenddate": "-",
            "actualtime": "-",
            "actualstarttime": "-",
            "actualendtime": "-",
            "name": [
                "Nihal Test"
            ],
            "timedate": [
                "07/15/2019 10:35 PM"
            ],
            "viewed": [
                "no"
            ],
            "response": [
                "Pending"
            ],
            "msgfromserviceprovider": [
                "-"
            ]
        },
        {
            "jobrequestid": "5d2d621746fac580993b3b86",
            "jobsnapshotid": "5d2d621746fac580993b3b84",
            "propertyname": "Sample Property",
            "address": "101 Main Street",
            "city": "San Francisco",
            "countrycode": "United States",
            "bedrooms": 3,
            "bathrooms": 2,
            "propertytype": "house",
            "accessinfo": "The lockbox with keys is at the top of the stairs, on the post opposite the front door. The code is 1234.",
            "garbageinfo": "The garbage cans are under the stairs leading up to the front door. Garbage is collected early on Monday morning.",
            "parkinginfo": "You can park your car on the street right in front of our garage. Parking is prohibited every second and fourth Monday of the month from 9am to 11am due to streetcleaning.",
            "wifiname": "WIFI Guest 2.4",
            "wifipassword": "password",
            "wifidescription": "-",
            "importantinfo": "Do not vacuum the cowhide rug in the home office - just shake it out. Vacuum all rugs, mop all hard floors, wipe all surfaces and light switches, clean all windows and glass surfaces, and disinfect toilet seats.",
            "offeredprice": 17,
            "duration": "-",
            "offeredpricecurrency": "USD",
            "canceledbyserviceprovider": "no",
            "canceledbyme": "no",
            "statusofrequest": "Pending",
            "msgtoserviceprovider": "T3",
            "scheduletime": "11:00 AM - 12:00 PM",
            "scheduleend": "07/17/2019",
            "schedulestart": "07/17/2019",
            "scheduleduration": 60,
            "jobsenddate": "07/15/2019",
            "job_title": "T3",
            "jobType": "Maintenance",
            "costs": [
                {
                    "reporterName": "Nihal Test",
                    "type": "mileage",
                    "value": 10,
                    "date": "2019-07-16T06:38:49.975Z",
                },
                {
                    "reporterName": "Nihal Test",
                    "type": "mileage",
                    "value": 145,
                    "date": "2019-08-02T05:50:44.679Z",
                },
                {
                    "reporterName": "Nihal Test",
                    "type": "duration",
                    "value": 15,
                    "date": "2019-08-02T05:50:52.707Z",
                },
                {
                    "reporterName": "Nihal Test",
                    "type": "cost",
                    "value": 150,
                    "date": "2019-08-02T05:51:01.157Z",
                }
            ],
            "totalCost": 0,
            "totalMileage": 0,
            "billableTime": 0,
            "slides": "0/4",
            "tasks": "0/8",
            "verificationphotos": "0/4",
            "problemsreported": 0,
            "problemslist": [],
            "title": "Sample: Simple",
            "description": "With just 4 photos you can create a simple checklist job and still get peace of mind your tasks were completed.\nThis checklist only has photos in the finish section and lets a host know when a pro started and finished the job; conveys exactly how a host wants the property set upon finish; gives peace of mind with visual proof the tasks were completed (photo required set); and has all of the property info. \nFor an example of a more thorough checklist check out the Sample: Complex in Sample Property.",
            "actualstartdate": "-",
            "actualenddate": "-",
            "actualtime": "-",
            "actualstarttime": "-",
            "actualendtime": "-",
            "name": [
                "Nihal Test"
            ],
            "timedate": [
                "07/15/2019 10:35 PM"
            ],
            "viewed": [
                "no"
            ],
            "response": [
                "Pending"
            ],
            "msgfromserviceprovider": [
                "-"
            ]
        },
        {
            "jobrequestid": "5d2d622746fac580993b3b91",
            "jobsnapshotid": "5d2d622746fac580993b3b8f",
            "propertyname": "Sample Property",
            "address": "101 Main Street",
            "city": "San Francisco",
            "countrycode": "United States",
            "bedrooms": 3,
            "bathrooms": 2,
            "propertytype": "house",
            "accessinfo": "The lockbox with keys is at the top of the stairs, on the post opposite the front door. The code is 1234.",
            "garbageinfo": "The garbage cans are under the stairs leading up to the front door. Garbage is collected early on Monday morning.",
            "parkinginfo": "You can park your car on the street right in front of our garage. Parking is prohibited every second and fourth Monday of the month from 9am to 11am due to streetcleaning.",
            "wifiname": "WIFI Guest 2.4",
            "wifipassword": "password",
            "wifidescription": "-",
            "importantinfo": "Do not vacuum the cowhide rug in the home office - just shake it out. Vacuum all rugs, mop all hard floors, wipe all surfaces and light switches, clean all windows and glass surfaces, and disinfect toilet seats.",
            "offeredprice": 18,
            "duration": "-",
            "offeredpricecurrency": "USD",
            "canceledbyserviceprovider": "no",
            "canceledbyme": "no",
            "statusofrequest": "Pending",
            "msgtoserviceprovider": "T4",
            "scheduletime": "11:00 AM - 12:00 PM",
            "scheduleend": "07/17/2019",
            "schedulestart": "07/17/2019",
            "scheduleduration": 60,
            "jobsenddate": "07/15/2019",
            "job_title": "T4",
            "jobType": "Inspection",
            "costs": [
                {
                    "reporterName": "Nihal Test",
                    "type": "mileage",
                    "value": 10,
                    "date": "2019-07-16T06:38:49.975Z",
                },
                {
                    "reporterName": "Nihal Test",
                    "type": "mileage",
                    "value": 145,
                    "date": "2019-08-02T05:50:44.679Z",
                },
                {
                    "reporterName": "Nihal Test",
                    "type": "duration",
                    "value": 15,
                    "date": "2019-08-02T05:50:52.707Z",
                },
                {
                    "reporterName": "Nihal Test",
                    "type": "cost",
                    "value": 150,
                    "date": "2019-08-02T05:51:01.157Z",
                }
            ],
            "totalCost": 0,
            "totalMileage": 0,
            "billableTime": 0,
            "slides": "0/4",
            "tasks": "0/8",
            "verificationphotos": "0/4",
            "problemsreported": 0,
            "problemslist": [],
            "title": "Sample: Simple",
            "description": "With just 4 photos you can create a simple checklist job and still get peace of mind your tasks were completed.\nThis checklist only has photos in the finish section and lets a host know when a pro started and finished the job; conveys exactly how a host wants the property set upon finish; gives peace of mind with visual proof the tasks were completed (photo required set); and has all of the property info. \nFor an example of a more thorough checklist check out the Sample: Complex in Sample Property.",
            "actualstartdate": "-",
            "actualenddate": "-",
            "actualtime": "-",
            "actualstarttime": "-",
            "actualendtime": "-",
            "name": [
                "Nihal Test"
            ],
            "timedate": [
                "07/15/2019 10:35 PM"
            ],
            "viewed": [
                "no"
            ],
            "response": [
                "Pending"
            ],
            "msgfromserviceprovider": [
                "-"
            ]
        },
        {
            "jobrequestid": "5d2d61f346fac580993b3b70",
            "jobsnapshotid": "5d2d61f246fac580993b3b6e",
            "propertyname": "Sample Property",
            "address": "101 Main Street",
            "city": "San Francisco",
            "countrycode": "United States",
            "bedrooms": 3,
            "bathrooms": 2,
            "propertytype": "house",
            "accessinfo": "The lockbox with keys is at the top of the stairs, on the post opposite the front door. The code is 1234.",
            "garbageinfo": "The garbage cans are under the stairs leading up to the front door. Garbage is collected early on Monday morning.",
            "parkinginfo": "You can park your car on the street right in front of our garage. Parking is prohibited every second and fourth Monday of the month from 9am to 11am due to streetcleaning.",
            "wifiname": "WIFI Guest 2.4",
            "wifipassword": "password",
            "wifidescription": "-",
            "importantinfo": "Do not vacuum the cowhide rug in the home office - just shake it out. Vacuum all rugs, mop all hard floors, wipe all surfaces and light switches, clean all windows and glass surfaces, and disinfect toilet seats.",
            "offeredprice": 15,
            "duration": "-",
            "offeredpricecurrency": "USD",
            "canceledbyserviceprovider": "no",
            "canceledbyme": "no",
            "statusofrequest": "Pending",
            "msgtoserviceprovider": "T1",
            "scheduletime": "11:00 AM - 12:00 PM",
            "scheduleend": "07/17/2019",
            "schedulestart": "07/17/2019",
            "scheduleduration": 60,
            "jobsenddate": "07/15/2019",
            "job_title": "T1",
            "jobType": "Turnover",
            "costs": [
                {
                    "reporterName": "Nihal Test",
                    "type": "mileage",
                    "value": 10,
                    "date": "2019-07-16T06:38:49.975Z",
                }
            ],
            "totalCost": 150,
            "totalMileage": 155,
            "billableTime": 15,
            "slides": "0/4",
            "tasks": "0/8",
            "verificationphotos": "0/4",
            "problemsreported": 0,
            "problemslist": [],
            "title": "Sample: Simple",
            "description": "With just 4 photos you can create a simple checklist job and still get peace of mind your tasks were completed.\nThis checklist only has photos in the finish section and lets a host know when a pro started and finished the job; conveys exactly how a host wants the property set upon finish; gives peace of mind with visual proof the tasks were completed (photo required set); and has all of the property info. \nFor an example of a more thorough checklist check out the Sample: Complex in Sample Property.",
            "actualstartdate": "-",
            "actualenddate": "-",
            "actualtime": "-",
            "actualstarttime": "-",
            "actualendtime": "-",
            "name": [
                "Nihal Test"
            ],
            "timedate": [
                "07/15/2019 10:34 PM"
            ],
            "viewed": [
                "no"
            ],
            "response": [
                "Pending"
            ],
            "msgfromserviceprovider": [
                "-"
            ]
        },
        {
            "jobrequestid": "5d2d624046fac580993b3b9c",
            "jobsnapshotid": "5d2d624046fac580993b3b9a",
            "propertyname": "Sample Property",
            "address": "101 Main Street",
            "city": "San Francisco",
            "countrycode": "United States",
            "bedrooms": 3,
            "bathrooms": 2,
            "propertytype": "house",
            "accessinfo": "The lockbox with keys is at the top of the stairs, on the post opposite the front door. The code is 1234.",
            "garbageinfo": "The garbage cans are under the stairs leading up to the front door. Garbage is collected early on Monday morning.",
            "parkinginfo": "You can park your car on the street right in front of our garage. Parking is prohibited every second and fourth Monday of the month from 9am to 11am due to streetcleaning.",
            "wifiname": "WIFI Guest 2.4",
            "wifipassword": "password",
            "wifidescription": "-",
            "importantinfo": "Do not vacuum the cowhide rug in the home office - just shake it out. Vacuum all rugs, mop all hard floors, wipe all surfaces and light switches, clean all windows and glass surfaces, and disinfect toilet seats.",
            "offeredprice": 19,
            "duration": "-",
            "offeredpricecurrency": "USD",
            "canceledbyserviceprovider": "no",
            "canceledbyme": "no",
            "statusofrequest": "Pending",
            "msgtoserviceprovider": "T5",
            "scheduletime": "11:00 AM - 12:00 PM",
            "scheduleend": "07/17/2019",
            "schedulestart": "07/17/2019",
            "scheduleduration": 60,
            "jobsenddate": "07/15/2019",
            "job_title": "T5",
            "jobType": "Other",
            "costs": [
                {
                    "reporterName": "Nihal Test",
                    "type": "mileage",
                    "value": 10,
                    "date": "2019-07-16T06:38:49.975Z",
                },
                {
                    "reporterName": "Nihal Test",
                    "type": "mileage",
                    "value": 145,
                    "date": "2019-08-02T05:50:44.679Z",
                },
                {
                    "reporterName": "Nihal Test",
                    "type": "duration",
                    "value": 15,
                    "date": "2019-08-02T05:50:52.707Z",
                }
            ],
            "totalCost": 0,
            "totalMileage": 0,
            "billableTime": 0,
            "slides": "0/4",
            "tasks": "0/8",
            "verificationphotos": "0/4",
            "problemsreported": 0,
            "problemslist": [],
            "title": "Sample: Simple",
            "description": "With just 4 photos you can create a simple checklist job and still get peace of mind your tasks were completed.\nThis checklist only has photos in the finish section and lets a host know when a pro started and finished the job; conveys exactly how a host wants the property set upon finish; gives peace of mind with visual proof the tasks were completed (photo required set); and has all of the property info. \nFor an example of a more thorough checklist check out the Sample: Complex in Sample Property.",
            "actualstartdate": "-",
            "actualenddate": "-",
            "actualtime": "-",
            "actualstarttime": "-",
            "actualendtime": "-",
            "name": [
                "Nihal Test"
            ],
            "timedate": [
                "07/15/2019 10:36 PM"
            ],
            "viewed": [
                "no"
            ],
            "response": [
                "Pending"
            ],
            "msgfromserviceprovider": [
                "-"
            ]
        }
    ],
    "headers": [
        "Property Title",
        "Address",
        "City",
        "Country Code",
        "Bedrooms",
        "Bathrooms",
        "Property Type",
        "Access Information",
        "Garbage Information",
        "Parking information",
        "Wifi Name",
        "Wifi Password",
        "Wifi Description",
        "Important Information",
        "Job Title",
        "Job Type",
        "Total Cost",
        "Billable Time",
        "Total Mileage",
        "Cost Value",
        "Cost Type",
        "Cost Added By",
        "Job Sent Date",
        "Scheduled Start Date",
        "Scheduled End Date",
        "Scheduled Time",
        "Scheduled Duration (mins)",
        "Actual Start Date",
        "Actual End Date",
        "Actual Time",
        "Actual Start Time",
        "Actual End Time",
        "Duration",
        "Status of Request",
        "Message to Service Provider",
        "Offered Price",
        "Offered Price Currency",
        "Canceled By Me",
        "Canceled By Service Provider",
        "Name",
        "Time & Date",
        "Viewed",
        "Response",
        "Message from Service Provider",
        "Slides",
        "Tasks",
        "Verification Photos",
        "Problems Reported",
        "Problems Reported Notes",
        "Title",
        "Description"
    ],
};

// 200 * 9 => default column width
const colum_width = 300 * 9 + 100 * 8 + 117 + 150 * 16 + 200 * 2 + 210 + 250 + 200 * 9;
console.log("colum_width : ", colum_width);

const COLUMN_WIDTHS = {
    propertyname: 300,
    slides: 100,
    actualstartdate: 150,
    actualenddate: 150,
    schedulestart: 150,
    scheduleend: 150,
    offeredpricecurrency: 250, // because of headline
    verificationphotos: 150,
    timedate: 150,
    msgfromserviceprovider: 210,
    actualtime: 150,
    actualstarttime: 150,
    actualendtime: 150,
    bedrooms: 100,
    bathrooms: 100,
    address: 300,
    jobsenddate: 150,
    accessinfo: 300,
    importantinfo: 300,
    propertytype: 150,
    tasks: 100,
    offeredprice: 150,
    msgtoserviceprovider: 300,
    canceledbyme: 150,
    problemsreported: 150,
    problemslist: 300,
    wifidescription: 300,
    parkinginfo: 300,
    viewed: 100,
    scheduletime: 150,
    scheduleduration: 150,
    garbageinfo: 300,
    description: 300,
    response: 117,
    job_title: 200,
    jobType: 200,
    totalCost: 100,
    bilableTime: 100,
    totalMilage: 100,
};

console.log("COLUMN_WIDTHS LENGTH : ", Object.keys(COLUMN_WIDTHS).length);

const ORDER_COLUMNS = [
    'propertyname',
    'address',
    'city',
    'countrycode',
    'bedrooms',
    'bathrooms',
    'propertytype',
    'accessinfo',
    'garbageinfo',
    'parkinginfo',
    'wifiname',
    'wifipassword',
    'wifidescription',
    'importantinfo',
    'job_title',
    'jobType',
    'totalCost',
    'billableTime',
    'totalMileage',
    'jobsenddate',
    'schedulestart',
    'scheduleend',
    'scheduletime',
    'scheduleduration',
    'actualstartdate',
    'actualenddate',
    'actualtime',
    'actualstarttime',
    'actualendtime',
    'duration',
    'statusofrequest',
    'msgtoserviceprovider',
    'offeredprice',
    'offeredpricecurrency',
    'canceledbyme',
    'canceledbyserviceprovider',
    'name',
    'timedate',
    'viewed',
    'response',
    'msgfromserviceprovider',
    'slides',
    'tasks',
    'verificationphotos',
    'problemsreported',
    'problemslist',
    'title',
    'description',
];

console.log("ORDER_COLUMNS LENGTH : ", ORDER_COLUMNS.length);